### PR TITLE
Session1

### PR DESCRIPTION
**Pull request by jyfernandez**
In this assignment, we created the implementation for querying the database using EF core.

### CODE REVIEW

**Review by JJRimorin — APPROVED** [review]
LGTM! Wait for Lai's review. Thanks!

**Comment by JJRimorin** [comment]
There's no base/main to merge this PR. Could you create a base branch first?

**Comment by jyfernandez** [comment]
> There's no base/main to merge this PR. Could you create a base branch first?

Is the base branch different from the main branch I have now? This PR is from branch session1 into the main branch.

**Comment by JJRimorin** [comment]
Pardon me, you have a branch but it does not allow updates. Could you change the settings for your base branch?

**Comment by jyfernandez** [comment]
> Pardon me, you have a branch but it does not allow updates. Could you change the settings for your base branch?

Apologies for that. I already updated the settings and I think you can merge updates now.

**Comment by JJRimorin** [comment]
Wait for Lai's review. Thank you!

**Comment by laira-salvador** [comment]
Looks Good!

**Pull request merged**
